version: '3'
services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    image: wpdocker/app
    ports:
     - "${WP_PORT}:80"
    environment:
      CONTAINER_ENV: "${WP_NAME:-local}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
      DB_DATABASE: "${DB_DATABASE:-wordpress_db}"
      DB_HOST: "${DB_HOST:-mysql}"
      DB_USERNAME: "${DB_USERNAME:-wordpress_user}"
      DB_PASSWORD: "${DB_PASSWORD:-secret}"
    volumes:
     - ./src:/var/www/html
     - ./tmp:/tmp
    networks:
     - wpdocker
  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
    image: wpdocker/node
    user: node
    volumes:
     - ./src:/var/www/html
    networks:
     - wpdocker
  mysql:
    image: mysql:5.7
    ports:
     - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_DATABASE: "${DB_DATABASE:-wordpress_db}"
      MYSQL_USER: "${DB_USERNAME:-wordpress_user}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      WP_TEST_DB_NAME: ${WP_TEST_DB_NAME:-wordpress_test_db}
    volumes:
     - wpdocker_mysql:/var/lib/mysql
     - ./docker/mysql/data:/docker-entrypoint-initdb.d
     # - ./docker/mysql/conf.d:/etc/mysql/conf.d
     # - ./docker/mysql/logs:/var/log/mysql
    networks:
     - wpdocker
networks:
  wpdocker:
    driver: "bridge"
volumes:
  wpdocker_mysql:
    driver: "local"